### ISSUE TITLE
Document how to set up a development environment with Docker

### ISSUE THREAD

**Issue by mstenta** [farmOS-legacy/farmOS.org#14]
There's an issue and pull request in the farmOS repo to add a Dockerfile:

https://github.com/farmOS/farmOS/issues/6
https://github.com/farmOS/farmOS/pull/8

We should add documentation to farmOS.org for people interested in using Docker for local farmOS development/hosting.

**Comment by mstenta** [comment]
These are the thing we should figure out and include:
- Setting up a MySQL container for the database.
- How to manage file storage?
- Document setup procedure.

**Comment by mstenta** [comment]
I started a new branch with an initial Docker documentation page: https://github.com/farmOS/farmOS.org/tree/docker

Let's use this issue and that branch to put together the setup instructions.

**Comment by thedude459** [comment]
So to setup a docker development environment on Ubuntu:

Docker setup - https://docs.docker.com/engine/installation/linux/ubuntulinux/
Git setup - https://docs.docker.com/v1.8/project/set-up-git/
Dev Environment - https://docs.docker.com/v1.8/project/set-up-dev-env/

**Comment by thedude459** [comment]
I am just posting this here in case you wanted to set yourself up with something now.  I am going to set myself up with one and I will document the procedure and try to push something to this repo.  Is there a way to tie a push to a certain issue?  I am not familiar with github.  I work on the mainframe.

**Comment by mstenta** [comment]
Thanks Matt! Any info you can provide is welcome!

If you want to work directly in Github, you can fork the farmOS.org repo, switch to the "docker" branch, and edit the file: docs/development/docker.md - that's the stub that I started.

It's all written in Markdown, so it's super simple. If you want to preview it locally, there are instructions for installing Mkdocs in the README.md. I find that to be very helpful - but not entirely necessary. You can do everything right in Github too if you want.

If you make any commits to the "docker" branch in your fork, just let us know in this issue! Or create a pull request when you think it's ready to go. Thanks again!

**Comment by rjcorwin** [comment]
@thedude459 @mstenta Using Docker for a development environment is going to be tricky with this repository because the source code isn't actually in this repository :P. How a Docker container is usually used for development is that you run the container plus an extra `--volume` option you use to map the code on your host machine into where the code is inside the container.

So let's say this repository did have all of the code. To develop we would then do...

```
docker run -p 80:80 --volume ./:/farmos farmos/farmos
```

But the problem is that the code isn't in this repository, it gets built into the image. It's not unusual to have code that gets built into an image from an outside source list using things like package manager lists and such (ex. npm's package.json, bower's bower.json, ruby's Gemfile, PHP's composer.json, etc.) but it is unusual to have YOUR code somewhere else. Your code being the code you want to work on that is not a dependency to just be included in referenced by a version number. 

@mstenta What are the downsides of moving all the farmOS specific modules into this repository?

**Comment by mstenta** [comment]
@rjsteinert Thanks for the explanation!

> @mstenta What are the downsides of moving all the farmOS specific modules into this repository?

Funny you should ask! I just started a discussion of the pros/cons of this here: https://www.drupal.org/node/2784927

Right now I'm still leaning towards keeping the modules in separate repositories (although I may move the theme into the distro). See that link for the reasoning - but it's not fully decided yet. In either case, it probably will not change during the 7.x-1.x branch of farmOS. If it were to change it would probably be in 8.x-2.x.

However, I don't think moving the farmOS specific modules into the distro repository will help with the Docker development quandry. Because there are other contrib modules+libraries+theme that would also need to be included somehow. So Drush Make would still need to be run either way.

It seems like the main question is: how do we provide a Docker environment for generalized Drupal contrib development? Because that's what would be really useful. When I'm developing farmOS, I'm often working on other contrib modules at the same time, each with their own repo (ie: Openlayers, Log module, etc). So having a Docker-based setup for general Drupal development might be nice.

But, maybe that's not what the goal of the farmOS Docker image is. In which case, this documentation page is a bit off the mark.

I'll need to get my feet wet with Docker a little more, and give it some more thought. Maybe we can talk about it in the next monthly call? If not before then...

**Comment by mstenta** [comment]
Another thing to consider with this... Drush Make by default will discard .git folders after it's done. You can prevent this by using the <code>--working-copy</code> flag.

```
drush make --working-copy build-farm.make farm
```

Perhaps we could somehow differentiate between Docker builds that are meant for development, and builds that are meant for use?

Could we run drush make locally to build the codebase with .git repos intact, and then mount that folder as a volume within the Docker instance?

**Comment by mstenta** [comment]
FYI: I did start writing out the "farmOS on Docker" documentation page a few days ago, forgot to post an update on that here.

You can view the current working version here: https://github.com/farmOS/farmOS.org/compare/docker

Currently it only has one sub-section "Local development" which has instructions for getting set up locally using Docker Compose. But @rjsteinert raises good points about whether or not that is actually usable for local development. So we can either change this doc to be more generally about using farmOS on Docker... or figure out how to also use it for development and update the doc accordingly.

**Comment by mstenta** [comment]
Another possibility (?): if we could use SSH on the docker container, we could use PHPStorm to develop locally and push changes to the container as a remote server. This is how I do local development currently using Vagrant + VirtualBox.

It sounds like adding SSH to docker is more work though...

**Comment by mstenta** [comment]
This is done! See http://farmos.org/development/docker/
