### ISSUE TITLE
Document standard practices

### ISSUE THREAD

**Issue by mstenta** [farmOS-legacy/farmOS.org#19]
farmOS provides a lot of flexibility in record keeping. It leaves it up to you to decide which log types to use for each type of activity you are performing.

For example: when you give an animal some medicine, do you use an Input log or a Medical log? What is the difference between an Activity and a Seeding?  Some of these are easy to answer, and some are hard.

Ultimately it depends on what you will be using the logs for later.  If one of the primary goals is to provide records to a certifying agency (Organic Cert, FDA, etc) then organizing them with that audience in mind makes the most sense, so perhaps that can be the starting point for defining some standard practices of record keeping in farmOS.

**Comment by symbioquine** [comment]
Seems like this issue could probably be closed in favor of https://farmos.discourse.group/t/creating-a-standard-interpretation-layer-on-top-of-core-farmos-schema/533/14

**Comment by mstenta** [comment]
Agreed @symbioquine - the forum has taken over as the place for these kind of discussions. Let's close some issues! :-)
