### ISSUE TITLE
Document Docker tagged release vs dev branch

### ISSUE THREAD

**Issue by mstenta** [farmOS-legacy/farmOS.org#20]
When the next version of farmOS is released, we will start creating "latest" tags in Docker Hub that build the latest stable tagged release of farmOS. Currently, the Docker image builds the 7.x-1.x dev branch.

We need to document on farmOS.org how to move from the dev branch to the tagged release.

We may also want to consider moving/splitting the Docker documentation so that it includes details for both development setups (7.x-1.x dev branch) and well as stable local hosting (tagged releases). It might make sense for the Docker page to exist under http://farmos.org/hosting instead of http://farmos.org/development

**Comment by mstenta** [comment]
These instructions should work for moving from a dev version to a tagged version, and also for upgrading from one tagged version to the next:

* Open the farmOS repo directory in terminal: `cd [farmOS-dir]`
* Stop and remove containers: `sudo docker-compose down`
* Checkout the new release version: `git checkout [new tag]`
* Backup files and database: `tar -czf data.tar.gz .data`
* Delete farm.info: `rm [farmOS-dir]/.data/www/profiles/farm/farm.info`
* Rebuild and start the containers: `sudo docker-compose up -d --build`
* Run Drupal updates: `sudo docker exec -it [www-container-name-or-id] drush updb` (or you can go to [yoursite]/install.php in a browser and run them there).

Replace the following:

* `[farmOS-dir]` - absolute path of the farmOS repository directory on your host system
* `[new tag]` - the farmOS version tag that you want to upgrade to (ie: `7.x-1.0-beta13`)
* `[www-container-name-or-id]` - the Docker container that farmOS is running in (the `www` container, not the `db` container). this can be found with `sudo docker ps`.
* `[yoursite]` - the URL of your local farmOS site... usually `http://localhost`

**Comment by mstenta** [comment]
Cross-referencing this issue where I am considering changing the volume mount point of the farmOS Docker image (and thereby changing how tagged release builds and development builds are created): https://github.com/farmOS/farmOS/issues/36

**Comment by mstenta** [comment]
This should also be part of the same effort: https://github.com/farmOS/farmOS/issues/45

**Comment by symbioquine** [comment]
Perhaps this issue can be closed now - seems like the dev/release tags part already documented; https://github.com/farmOS/farmOS.org/blame/063ffc82ad075e3c36fd5df6616c9032590b9815/docs/hosting/docker.md#L13-L32
