### ISSUE TITLE
Consider merging 7.x-1.x documentation into farmOS repository

### ISSUE THREAD

**Issue by mstenta** [farmOS-legacy/farmOS.org#22]
This farmOS.org documentation repository is currently separate from the core farmOS repo. In the 8.x-2.x branch of farmOS I have decided to include the documentation directly in the repo. Should we merge this repo into the 7.x-1.x branch for consistency?

**Comment by mstenta** [comment]
Considerations:

* This Github repo can't be forwarded to the farmOS one, so we would need to "archive" it somehow, and make it clear that future work should be done in the farmOS repo
* All issues in this Github repo would need to be copied to the farmOS repo
* Because Github pages are used to host farmOS docs, we would only be able to have one gh-pages branch in the farmOS repo. Currently, that branch is being used for the 8.x-2.x documentation (http://8x-2x.farmos.org). So if we wanted to host both, we'd need to figure out another way.

**Comment by mstenta** [comment]
> So if we wanted to host both, we'd need to figure out another way.

One approach might be to put BOTH the 7.x-1.x and 8.x-2.x documentation into the same site (instead of having two separate sites).  MkDocs doesn't currently support multiple versions of docs natively (see https://github.com/mkdocs/mkdocs/issues/193), but someone built a tool that helps you accomplish that: https://pypi.org/project/mike/.

It might also be worth migrating from MkDocs to another more flexible static site generator. I've experimented with Hugo a bit recently and it's pretty flexible: https://gohugo.io/

**Comment by mstenta** [comment]
Made a new issue for considering Hugo: https://github.com/farmOS/farmOS.org/issues/32

**Comment by symbioquine** [comment]
Seems like this issue could probably be closed now since the farmOS repository is being used to host the 2.x documentation on Github pages and I don't think you can host more than one site on the same repository.

**Comment by mstenta** [comment]
Yes true - the newer thinking is that we'll keep this repository separate and use it for the "community portal" website, which either links to the 2.x docs or pulls them in via Gatsby.

Here is the forum thread on that, for future reference: https://farmos.discourse.group/t/farmos-org-redesign/505

**Comment by mstenta** [comment]
This issue came back to mind this morning. I'm going to reopen it.

I think it might still be worth considering merging this repo's 7.x-1.x branch specifically into the farmOS 7.x-1.x branch, perhaps at the same time that we make 2.x the new default branch: https://www.drupal.org/project/farm/issues/3162807

Some of the reasoning for this is described here (related to merging the 7.x-1.x branch of farmOS itself into 2.x when the time comes): https://www.drupal.org/project/farm/issues/3162606

A lot of the farmOS.org content right now is very specific to 7.x-1.x, and will need to be rewritten/refactored for 2.x anyway. By merging it into farmOS, we both a) get all that history preserved in the same place as the old code, and b) provides a clean break to start fresh with the farmOS.org repository as we move forward with https://farmos.discourse.group/t/farmos-org-redesign/505

We can pick and choose what we want to include in the new redesign (if anything), and also what to "pull in" from the 2.x branch of the farmOS repo via Gatsby.

So I sort of see this as more of an "archival" task now ... as we take the big step into the new 2.x world and put 7.x-1.x behind us. We would still keep the farmOS.org repository for the community site moving forward.

Still some things to figure out with this, but I wanted to at least get these thoughts down and reopen the issue.

**Comment by mstenta** [comment]
I've completed a comprehensive port of all https://farmOS.org/hosting documentation to the farmOS 2.x repository docs, as well as "Local HTTPS" setup instructions (adapted from https://github.com/farmOS/farmOS.org/blob/7.x-1.x/docs/development/configure-local-https-reverse-proxy.md).

I also moved https://2x.farmos.org to https://docs.farmos.org, in preparation for future community portal development on farmOS.org itself.

The remaining sections of farmOS.org that need to be considered are:

- [ ] `/docs/app` (keep this on the portal site at the same URL)
- [ ] `/docs/community` (all of this can be reorganized into the community portal)
- [ ] `/docs/development/api.md` (2.x API documentation needs to be written)
- [ ] `/docs/development/client.md` (perhaps this should move to the `README.md` in Field Kit?)
- [ ] `/docs/development/drupal.md` (we can drop this)
- [ ] `/docs/development/issue-queues.md` (just a link to `CONTRIBUTING.md`, I think we can drop this)
- [ ] `/docs/development/projects.md` (can be simplified to a "Community projects" page on the portal perhaps? maybe this section includes contrib documentation?)
- [ ] `/docs/development/release.md` (TBD)
- [ ] `/docs/development/update-safety.md` (perhaps this warning should be somewhere in the new 2.x self-hosting docs)
- [ ] `/docs/guide` (update/port to farmOS 2.x repo?)
- [x] `/docs/hosting/localization.md` (this is the only hosting-related doc left to port)
- [ ] `/docs/donate.md` (keep on portal site)
- [ ] `/docs/faq.md` (turn this into a forum topic?)
- [ ] `/docs/index.md` (rework into a new community portal homepage)

**Comment by mstenta** [comment]
> `/docs/hosting/localization.md` (this is the only hosting-related doc left to port)

I added a todo to https://www.drupal.org/project/farm/issues/3159886 for this one, so we can consider all of the `/docs/hosting` pages "figured out". That one will be rewritten specifically for 2.x localization.

**Comment by symbioquine** [comment]
Nice work! In future I'd be happy to help with maintaining my contributions - like that reverse proxy documentation.

Not a big deal either way, but just curious whether there's a reason why you chose to ditch `mkcert` in the "Local HTTPS" setup instructions? It simplifies the command-line one-liner needed to include the certificate Common Name and handles the work of automatically registering the test CA locally - to avoid self-signed certificate warnings. (It also has pretty [good concise documentation](https://github.com/FiloSottile/mkcert) which is part of why I chose to include it.)

**Comment by mstenta** [comment]
Thanks @symbioquine ! I found myself in a flow going through all the other stuff so the local https stuff just happened alongside it. Happy to have your help maintaining these things moving forward of course! :-)

> Not a big deal either way, but just curious whether there's a reason why you chose to ditch mkcert in the "Local HTTPS" setup instructions?

Oh I didn't have any elaborate reasoning behind that change... I basically just merged the original docs with some of my own standard practices, which up until now have used `openssl` and a self-signed certificate. I also figured it would avoid the extra dependency on `mkcert`, which I was unfamiliar with, and so felt a bit more elegant (`openssl` is installed by default on Ubuntu).

> It simplifies the command-line one-liner needed to include the certificate Common Name and handles the work of automatically registering the test CA locally - to avoid self-signed certificate warnings.

Ah I actually didn't know that about `mkcert`! That is handy!

What if we add something like "Alternatively, you can use `mkcert` to ... which helps to ..."?

**Comment by symbioquine** [comment]
> Oh I didn't have any elaborate reasoning behind that change... I basically just merged the original docs with some of my own standard practices, which up until now have used `openssl` and a self-signed certificate. I also figured it would avoid the extra dependency on `mkcert`, which I was unfamiliar with, and so felt a bit more elegant (`openssl` is installed by default on Ubuntu).
> 
> > It simplifies the command-line one-liner needed to include the certificate Common Name and handles the work of automatically registering the test CA locally - to avoid self-signed certificate warnings.

Makes sense. Agreed it's more likely for the openssl command to be already installed (or trivial to get installed) out of the box.

> Ah I actually didn't know that about `mkcert`! That is handy!
> 
> What if we add something like "Alternatively, you can use `mkcert` to ... which helps to ..."?

Yeah, that would work. I can send a PR to that effect if it would help...

**Comment by mstenta** [comment]
FYI there has been more discussion about these ideas in the forum: https://farmos.discourse.group/t/farmos-org-redesign/505

**Comment by mstenta** [comment]
I plan to merge `7.x-1.x` of this repo into `7.x-1.x` of the farmOS repo (just to preserve history, not files), followed by doing the same for farmOS `7.x-1.x` into `2.x`, per https://www.drupal.org/project/farm/issues/3162606

We will be archiving this repository and replacing it with https://github.com/farmOS/farmos.org-EXPERIMENTAL - so that will serve to preserve history and contributions in the farmOS repo itself.
