### ISSUE TITLE
Consider moving to Hugo for static site generation

### ISSUE THREAD

**Issue by mstenta** [farmOS-legacy/farmOS.org#32]
We currently use [Mkdocs](https://www.mkdocs.org/) to generate farmOS.org as a static site from Markdown files. Mkdocs is nice because it is very simple, provides a default template (no theming necessary), and focuses on creating documentation.

[Hugo](http://gohugo.io/) is another static site generator that is more general (not specific to documentation). We may want to consider transitioning to Hugo in the future to give us more flexibility. Hugo provides some things that Mkdocs does not, like URL aliases/redirects (we're currently hacking that in with some custom JS), and it would allow more than 2 levels of menus (which is a pretty big limitation for us now, especially as the farmOS.org User Guide grows).

It may also allow us to host documentation for both the 7.x-1.x branch and the 8.x-2.x branch in the same repo, and potentially merge all of that directly into the farmOS repo itself (https://github.com/farmOS/farmOS.org/issues/22).

**Comment by mstenta** [comment]
Closing in favor of #76

**Comment by jgaehring** [comment]
> Closing in favor of #76

Didn't close.
