### ISSUE TITLE
Move hangout timing to a more convenient time (for me)

### ISSUE THREAD

**Issue by roryfogerty** [farmOS-legacy/farmOS.org#34]
Hi
Current Hangout timing of 1pm EDT equates to 5am in New Zealand. I'd love to be part of the call but find 5am a bit outside my comfort zone.

Propose we change the time to 2pm EDT starting with the August hangout.

Anyone have an problem with this. If so, please propose another time
Thanks
Rory

**Comment by mstenta** [comment]
I'm fine with moving it ahead 1 hour. I posted a link to this issue on Twitter (https://twitter.com/getFarmier/status/1017117801687941120) and in the Riot chat (https://riot.im/app/#/room/#farmOS:matrix.org). Let's see if anyone else has thoughts.

**Comment by CFWHISPERER** [comment]
Yes this time is fine for me and I think it would be a good time for me to join in, can you remind if the date of the next one?

**Comment by mstenta** [comment]
Next one is scheduled for August 8th (https://farmos.org/community/monthly-call/)

**Comment by mstenta** [comment]
3 people replied and all said that changing to 2 pm would be fine. I updated the schedule for the rest of 2018: https://farmos.org/community/monthly-call/

Note that daylight savings time ends on November 4th, so 2 pm Eastern will be 7 pm UTC for the November and December calls. I think that means it will be another extra hour later for you @roryfogerty - correct?
