### ISSUE TITLE
Document REST API

### ISSUE THREAD

**Issue by mstenta** [farmOS-legacy/farmOS.org#4]
Add information about how to use the REST API endpoints provided by the [Restful Web Services](http://drupal.org/project/restws) module.

**Comment by BFAFisher** [comment]
Just reviewed REST top level. Comment was that it was going to be built into Drupal 8. What are the implications for both this and the mobile project? I would suggest that we encapsulate the REST API services so that we can update the API as necessary without impacting our other code.

**Comment by mstenta** [comment]
@BFAFisher Yea Drupal 8 has a rest module in core, which was inspired by the Restful Web Services module available for Drupal 7 (http://drupal.org/project/restws). More info: https://www.drupal.org/docs/8/core/modules/rest/overview

farmOS is built on Drupal 7, and it includes the Restful Web Services module. When we upgrade farmOS to Drupal 8, it will use the core Rest module.

For the most part, the API should be the same, but there will probably be some differences. Since there are probably going to be some other architectural changes between farmOS 1.x and 2.x (Drupal 7 and Drupal 8 versions, respectively), it may be unavoidable that we have a 1.x and 2.x version of the API. I don't think this will be a huge issue for the mobile app, because so far the things we've been talking about mostly revolve around logs, and those aren't going to change much in D8.  In fact, there is already a release of the Log module for Drupal 8, so we could do some comparisons between the D8 core Rest module and the D7 contrib RESTful Web Services module. My guess is that they won't be all that different, but it would be good to know for sure.

**Comment by mstenta** [comment]
@alexadamsmith is working on an iOS native app for farmOS (https://github.com/farmOS/farmOS-mobile-app) and he and I have been working through some of the REST API details over in this issue: https://github.com/farmOS/farmOS-mobile-app/issues/3

Lot of good info in that conversation that we should incorporate into this documentation.

**Comment by mstenta** [comment]
Here are some other issues that contain some good information about using the farmOS API:

https://github.com/farmOS/farmOS-native/issues/2
https://github.com/farmOS/farmOS-native/issues/12

**Comment by mstenta** [comment]
I added an initial API documentation page to farmOS.org with example curl commands for querying and creating records: https://farmos.org/development/api/

We can add to that moving forward, but I'm going to close this issue now that the initial page is up.
