### ISSUE TITLE
Running behind reverse proxy

### ISSUE THREAD

**Issue by drewbyp** [farmOS-legacy/farmOS.org#62]
Pre install, how can I configure the base url so that I can correctly run FarmOS behind a reverse proxy. My only option at the moment is to use IIS as the reverse proxy but some resources are being blocked because they're not served over the secure endpoint. 

Thanks

**Comment by mstenta** [comment]
This might be better suited as a forum post, in the hosting category. I copied this over and will respond in that thread: https://farmos.discourse.group/t/running-behind-reverse-proxy/108

**Comment by drewbyp** [comment]
Perfect. Thank you
