### ISSUE TITLE
Home page mobile layout is broken by video embeds 

### ISSUE THREAD

**Issue by jgaehring** [farmOS-legacy/farmOS.org#63]
The homepage is not displaying responsively on mobile because the video embeds are breaking the layout. This is especially an issue with the menu, which is pushed off the screen. 

![Screenshot_20191013-103240](https://user-images.githubusercontent.com/5556545/66717405-a92a8180-eda6-11e9-97e3-5b6c902f90a7.png)

![Screenshot_20191013-103236](https://user-images.githubusercontent.com/5556545/66717409-b5164380-eda6-11e9-97d1-60ef228f67f5.png)

![Screenshot_20191013-103219](https://user-images.githubusercontent.com/5556545/66717412-bb0c2480-eda6-11e9-8246-0bf4fdac7fc8.png)

**Comment by mstenta** [comment]
Thanks for opening a bug report for this - it's been a known issue for a while. I'll take a quick stab at it right now and see what I can do...

**Comment by mstenta** [comment]
It doesn't happen in Firefox with Responsive Design Mode for whatever reason. So I might just have to test on the live site.

Looks like this is the way to do it with Bootstrap:

https://stackoverflow.com/questions/25228056/responsive-iframe-using-bootstrap

**Comment by jgaehring** [comment]
> Looks like this is the way to do it with Bootstrap:

Oh cool, looks pretty straight-forward. Let me know if you need any help with it. I opened this up so I would have a chance to circle back around to it at some point this week, so if you're not able to resolve it, let me know and/or feel free to assign it to me.

**Comment by mstenta** [comment]
It appears the `embed-responsive embed-responsive-16by9` Bootstrap classes don't work. This may be because the Mkdocs Bootstrap version is 3.0.3 :-(

**Comment by mstenta** [comment]
IIRC Bootstrap themes have been split out of Mkdocs to their own repo: https://mkdocs.github.io/mkdocs-bootstrap/

So I think we need to update to use that.

**Comment by jgaehring** [comment]
Oh ok. I was just looking at the section on [Customizing a Theme](https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme). Could be a useful backup solution, or a temporary fix if we don't want to deal with migrating the theme right away.

**Comment by mstenta** [comment]
Ah actually I think this is what we want: https://mkdocs.github.io/mkdocs-bootswatch/

(Because we use the Yeti Bootswatch of Bootstrap)

**Comment by mstenta** [comment]
Oh wait - I'm already using `mkdocs-bootswatch` locally. So maybe *that* doesn't have the newer version of Bootstrap. :-/

**Comment by mstenta** [comment]
I tried simply changing the theme to `bootstrap` instead of `yeti` and the embed videos seem to work responsively in that.

Should we just change to the basic Bootstrap theme instead of the Yeti bootswatch?

**Comment by mstenta** [comment]
> Should we just change to the basic Bootstrap theme instead of the Yeti bootswatch?

Bah! This breaks the menu! Menu items with a second level to them (eg: "Managing assets") don't display the lower level items when you hover over them. :man_facepalming:

**Comment by mstenta** [comment]
We could consider switching to the `readthedocs` theme. I used that as a placeholder for the 8.x-2.x docs: http://8x-2x.farmOS.org, for example.

It looks OK - not sure I love it for farmOS.org though.

Ultimately we probably need to consider moving to something other than Mkdocs for farmOS.org - but that's a much bigger issue.

**Comment by mstenta** [comment]
> Oh ok. I was just looking at the section on Customizing a Theme. Could be a useful backup solution, or a temporary fix if we don't want to deal with migrating the theme right away.

Maybe this is the best approach in the short term, @jgaehring

**Comment by mstenta** [comment]
I replicated Bootstrap's responsive embed CSS classes in a new `extra.css` file: https://github.com/farmOS/farmOS.org/commit/e3121523bb877a65a11917691a4f3ee458e772c1

And then wrapped all embedded videos with the proper classes: https://github.com/farmOS/farmOS.org/commit/7b5d4b9bf9f4d6a1425674d9c262e10b865a7b58

Deployed these changes to the live site - waiting for it to update so I can test on my phone...

**Comment by mstenta** [comment]
Looks like it's fixed! @jgaehring can you confirm and close this issue?

**Comment by jgaehring** [comment]
Looks good to me!
