### ISSUE TITLE
Add server requirements to Field Kit page

### ISSUE THREAD

**Issue by jgaehring** [farmOS-legacy/farmOS.org#69]
It's come up a few times that users are trying to connect Field Kit to their farmOS server that is not running with an SSL cert (ie, on http instead of https). I need to remember to add a requirements section for Field Kit. I'm wondering, however, if this should include a link to the docs being added by PR #66, for configuring https and a reverse proxy on local networks.

**Comment by mstenta** [comment]
PR https://github.com/farmOS/farmOS.org/pull/66 has been merged and deployed: https://farmos.org/development/configure-local-https-reverse-proxy/

**Comment by jgaehring** [comment]
Thinking now about also including require farmOS version for Field Kit. That might require being updated frequently, unless we just said something to the effect of "requires latest farmOS version", but then that might not always be true. Hmm... :thinking:

**Comment by mstenta** [comment]
Oh we should increment the `api` version in `/farm.json`. Then Field Kit could just check that. It's not the same as the farmOS version. I've only be incrementing it when the actual API changes.

**Comment by mstenta** [comment]
Done: https://github.com/farmOS/farmOS/commit/9f86cb0099dffad365d6d191b49ebdf7d552e182

**Comment by jgaehring** [comment]
Oh cool. Hmm, I still wondering how to document that and/or check for that programatically within FK itself.

**Comment by mstenta** [comment]
Oh whoops - I commented on the wrong issue, sorry. I thought this was https://github.com/farmOS/farmOS/issues/231 - so it's not relevant to this (but is to that).

**Comment by mstenta** [comment]
> unless we just said something to the effect of "requires latest farmOS version", but then that might not always be true.

I think that would be a fair thing to say. It might not always be true, but it's better safe than sorry, generally speaking.

**Comment by jgaehring** [comment]
Yea, better safe than sorry is probably a good approach.

It also occurs to me that we might want to get to a point with FK where part of the criteria for how "stable" it is would be how frequently it requires corresponding updates to the farmOS API.

**Comment by mstenta** [comment]
Merged https://github.com/farmOS/farmOS.org/pull/81
