### ISSUE TITLE
Redesign site with Gatsby

### ISSUE THREAD

**Issue by jgaehring** [farmOS-legacy/farmOS.org#76]
I started playing around with this during It's My farmOS! and figured I'd leave some notes here on my findings and the steps I think we need to take going forward.

One thing that occurred to me was that I want to be careful how I duplicate and/or move files around so that git is able to track the files' history. When I scaffolded the Gatsby project, I put it into its own separate directory, `gatsby/`, but would eventually like to move everything in there up to the level of root. My first inclination was to copy all the markdown files into `gatsby/content/` but I realized if I `git add`ed these w/o `git rm`ing the original files in the same commit, git would not be tracking these as renamed files, but as totally new files, which would not retain the original file history. So I think I either need to `mv` all the file right off the bat, or perhaps create some test markdown files and paths while I work on layout and configuration, then `mv` the files when everything is all said and done, and I'm ready to move it all up to root.

I am using the [gatsby-starter-blog](https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-blog/) template, and one issue that came up immediately was that it did not preserve the full relative path for individual pages; eg, instead of getting the url `http://localhost:8000/guide/quick` for the file `gatsby/content/guide/quick.md`, we're getting `http://localhost:8000/quick`. The solution I found for this was to modify the `gastby-source-filesystem` plugin in `gatsby-config.js` as such:

```js
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content`,
        name: `site`,
      },
    },
```

I actually reverted this change, because I wanted to give more thought to the git history as mentioned above, but it should be easy to reproduce.

Another consideration is that with Gatsby we have the opportunity to provide separate [layouts](https://www.gatsbyjs.org/docs/layout-components/) for the User Guide vs the Community pages vs etc. I think we may want to start conservatively here, but it would be nice to think about how their needs may differ and how we can handle that in the layout. I think for starters we will want to configure the `gatsby-source-filesystem` plugin to separate the content into layout types (another reason to hold off configuring that right away). We'll also need to modify `gastby-node.js` to use separate layout components when `createPages` is called.

I think the first step should be to prototype some layouts in Figma, so we have a better idea what those different layout types should be.

Sidenote regarding layouts: found a helpful plugin, [gatsby-remark-table-of-contents](https://www.gatsbyjs.org/packages/gatsby-remark-table-of-contents/), which can help us reproduce the table of contents like we currently are in the left margin of each page.

Also, do we want to close #32?

**Comment by mstenta** [comment]
> Also, do we want to close #32?

Let's do it!

Also copying over some of the important points (in my mind) from that issue description so they aren't lost/forgotten:

> Hugo provides some things that Mkdocs does not, like URL aliases/redirects (we're currently hacking that in with some custom JS), and it would allow more than 2 levels of menus (which is a pretty big limitation for us now, especially as the farmOS.org User Guide grows).

> It may also allow us to host documentation for both the 7.x-1.x branch and the 8.x-2.x branch in the same repo, and potentially merge all of that directly into the farmOS repo itself (#22).

**Comment by mstenta** [comment]
Regarding the deployment plan for this branch... I would recommend thinking about it in the same way that you would think about a "live site migration". Build the branch in a way that is easy to rebase again and again until it's ready to go live - at which point we pull the trigger and move all the pages in their current state to their new location.. There will inevitably be changes to the live master branch in the meantime, and dealing with rebase/merge conflicts would be very annoying. The work done in this branch should never become a blocker for updates in the master branch, in other words.

**Comment by jgaehring** [comment]
> Hugo provides some things that Mkdocs does not, like URL aliases/redirects (we're currently hacking that in with some custom JS)

A couple of ways this is possible. At its core, Gatsby has the [`createRedirect`](https://www.gatsbyjs.org/docs/actions/#createRedirect) action for doing just this. That could also be facilitated with [`gatsby-plugin-netlify`](https://www.recurse.com/), and with Netlify's [`_redirects`](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file) file.

> and it would allow more than 2 levels of menus (which is a pretty big limitation for us now, especially as the farmOS.org User Guide grows).

Yea, there's no limit to what's possible there. Although I think it might also be useful to think about design here, and whether we really want to have menus nested so many levels deep, or if we want to take another approach. Thinking primarily of this: 

> Another consideration is that with Gatsby we have the opportunity to provide separate [layouts](https://www.gatsbyjs.org/docs/layout-components/) for the User Guide vs the Community pages vs etc.

For instance, to once again use the Gatsby site itself as a source of inspiration, I like the way they provide a dedicated nav panel on their [Docs](https://www.gatsbyjs.org/docs/) page. I think it would be nice to do something like that for the User Guide, while it wouldn't be necessary for, say, the Community pages.

> It may also allow us to host documentation for both the 7.x-1.x branch and the 8.x-2.x branch in the same repo, and potentially merge all of that directly into the farmOS repo itself (#22).

Ah, yes, I'd love to talk more about this too. And once again, it looks like there's a plugin for that: [`gatsby-source-git`](https://www.gatsbyjs.org/packages/gatsby-source-git/).

> Build the branch in a way that is easy to rebase again and again until it's ready to go live - at which point we pull the trigger and move all the pages in their current state to their new location.. There will inevitably be changes to the live master branch in the meantime, and dealing with rebase/merge conflicts would be very annoying. The work done in this branch should never become a blocker for updates in the master branch, in other words.

Yes! In fact, I came to some of the same conclusions in chat with @paul121:

> I'm also thinking, given that this redesign may take a long time, and there are likely to be ongoing changes to the docs while that is happening, it will make merging that stuff in at the end a lot easier
>
> which is why I'm currently favoring the latter of these two options:
>> So I think I either need to mv all the file right off the bat, or perhaps create some test markdown files and paths while I work on layout and configuration, then mv the files when everything is all said and done, and I'm ready to move it all up to root.
>
> that way it's super easy to periodically rebase on the 7.x-1.x without any merge conflicts in the original files, while I keep working on the design in that separate gatsby/ directory

**Comment by jgaehring** [comment]
Thinking more about this, perhaps the git workflow could go something like this:

- `cp` markdown files from `/docs/` to `/gatsby/content/` to experiment with
- ...
- :sparkles: magically create a beautiful brand new site design :sparkles:
- :zap: rebase frequently :zap: 
- ...
- `rm` copied markdown files in `/gatsby/content/` directory (one commit)
- `mv` markdown files from `/docs/` to `/gatsby/content/` then `mv` everything from `/gatsby/` up to `/` and `rm` the `/docs/` and `/gatsby/` directories (one commit)

That should preserve git history and allow frequent rebases w/o conflicts.

**Comment by jgaehring** [comment]
I think this can be closed. See the new repo: https://github.com/farmOS/farmOS.org-EXPERIMENTAL
