### ISSUE TITLE
Update Field Kit docs with Instructions for configuring farm_access

### ISSUE THREAD

**Issue by jgaehring** [farmOS-legacy/farmOS.org#92]
I realized we never really documented this, I guess because we had farmos.app as a default, but I think it would be good to add to documentation once we merge in the `multiple_origins` branch (farmOS/farmOS#271) so anyone can add additional clients to their list of allowed origins. Realizing this would be good for farmOS/farmOS-client#214, as well, if someone wants to host a fork of Field Kit in another language.

Leaving this issue here in the hopes I'll remember to do so.

**Comment by mstenta** [comment]
https://github.com/farmOS/farmOS/issues/271 was merged! :-)

**Comment by mstenta** [comment]
Closing this as "outdated"...
