### ISSUE TITLE
Move FAQ to forum?

### ISSUE THREAD

**Issue by mstenta** [farmOS-legacy/farmOS.org#98]
Just had this idea a moment ago: rather than maintaining a FAQ page on farmOS.org, perhaps we should just create a pinned forum topic that we use to organize frequently asked questions (along with links to relevant forum posts).

farmOS Forum: https://farmOS.discourse.group

Something to consider during the Gatsby redesign perhaps? #76

**Comment by jgaehring** [comment]
Oh this is a great idea! I wonder if it might even be possible to embed that topic back into farmOS.org.

**Comment by jgaehring** [comment]
https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963

**Comment by mstenta** [comment]
Closing this as "outdated" - we are in the process of making https://github.com/farmOS/farmos.org-EXPERIMENTAL the new canonical repository for farmOS.org. The old site will be moved to https://v1.farmos.org, and we will be sure to redirect to the old FAQ from the new site.

If we want to pick up the idea of a FAQ again for the new site (or make one in the forum instead) we can make those decisions when/where we need to.
